index:
    path: /
    controller: App\Controller\CustomerController::form
success:
    path: /success
    controller: App\Controller\SuccessController:success
list:
    path: /list
    controller: App\Controller\ListController:list